#!/usr/bin/env bash

GUIDESTRIPE=72
OVERWRITE=false

usage() {
  echo "Usage: $0 [options]"
  echo
  echo "Sets initial nano editor settings for the current user."
  echo
  echo "Toggles the constant display of the current line, column,"
  echo "and character positions."
  echo
  echo "Options:"
  echo "  -h, --help                            Displays help on commandline options"
  echo "  -s, --stripe, --guidestripe <number>  Draws a vertical stripe for helping"
  echo "                                        to judge the width of the text."
  echo "                                        Default: 72"
  echo "  -o, --overwrite                       Overwrite existing ~/.nanorc"
}

if ! OPTS="$(getopt \
  --longoptions help,stripe:,guidestripe:,overwrite \
  --options hs:o \
  --name "$(basename "$0")" \
  -- "$@"
)"; then
  usage
  exit 1
fi
eval set -- "$OPTS"
while true; do
  case "$1" in
    --help|-h) usage; exit ;;
    --guidestripe|--stripe|-s) GUIDESTRIPE="$2"; shift 2 ;;
    --overwrite|-o) OVERWRITE=true; shift ;;
    --) shift; break ;;
    *) echo "DEBUG: No implementation for the option $1" ; exit 1 ;;
  esac
done
ARGS=("$@")
ARGCOUNT=${#ARGS[@]}
if [ "${ARGCOUNT}" -gt "0" ]; then
  echo "$0: Unexpected arguments supplied."
  usage
  exit 1
fi

if $OVERWRITE || [ ! -f ~/.nanorc ]; then
  echo set constantshow > ~/.nanorc
  echo set guidestripe $GUIDESTRIPE >> ~/.nanorc
else
  echo ~/.nanorc found. Not overwriting.
  echo To overwrite:
  echo $ $0 --overwrite
fi
