#!/usr/bin/env bash
#
# Create vm-utility development environment inside a new VM instance.
#
# Installs Multipass tool if not already installed.
# Launches a new Multipass instance using mp-launch tool.
# On the launched instance:
# - Creates a workspace directory and clones the vm-utility there.
# - Sets up vm-utility and Multipass tools in the VM.
# - With --branch option, checkouts a new local branch.
# - Creates a simple initial configuration file for nano.
# - Sets up your identity (--name and --email options)
# and configures the default text editor (--editor option) for Git.
# - Generates a new SSH key on the instance and prints the public key.
# - Forces access to GitHub repositories via SSH always replacing HTTPS
# URLs with SSH ones in the VM.
#
set -e

#######################################
# Includes
#######################################
. vmu-calls

#######################################
# DEFAULT VALUES
#######################################

CPUS="4"
DISK="128G"
MEMORY="16G"
VM_NAME="primary"
MOUNT=
IP=
WORKSPACE=/home/ubuntu/workspace
VMU_DIR=$WORKSPACE/vm-utility
VMU_URL=https://github.com/mkaapu/vm-utility.git
CHECKOUT_ARGS=( "--url=$VMU_URL" "$VMU_DIR" )
SETUP_ARGS=( "--nano" "--ssh" )

#######################################
# USAGE
#######################################

usage() {
  echo "Usage: $0 [options]"
  echo
  echo "Creates and starts a new VM for vm-utility development."
  echo
  echo "Example:"
  echo "$ $0 -n \"Peter Parker\" -a peter.parker@gmail.com -e nano -b web-dev spider-verse"
  echo
  echo "Options:"
  echo "  -h, --help                            Displays help on commandline options"
  echo "  -n, --name \"<user.name>\"              \"Your name\" (for git config)"
  echo "  -a, --email <user.email>              Your email address (for git config)"
  echo "  -e, --editor <core.editor>            Your text editor (for git config)"
  echo "                                        Default: nano"
  echo "  -b, --branch <branch>                 Name of a branch to checkout"
  echo "  -c, --cpus <cpus>                     Numbers of CPUs to allocate."
  echo "                                        Minimum: 1, default: 4."
  echo "  -d, --disk <disk>                     Disk space to allocate. Positive"
  echo "                                        integers, in bytes, or with K, M, G"
  echo "                                        suffix."
  echo "                                        Minimum: 512M, default: 128G."
  echo "  -m, --memory <mem>                    Amount of memory to allocate. Positive"
  echo "                                        integers, in bytes, or with K, M, G"
  echo "                                        suffix"
  echo "                                        Minimum: 128M, default: 16G."
  echo "  -i, --ip <ip>                         Sets a static IP address for the"
  echo "                                        instance. Note that there will be no"
  echo "                                        IP address conflict detection with"
  echo "                                        any existing addresses."
  echo "  --mount <local-path>:<vm-path>        Mount a local directory inside the"
  echo "                                        instance. If <vm-path> is omitted,"
  echo "                                        the mount point will be the same as the"
  echo "                                        absolute path of <local-path>"
  echo "Arguments:"
  echo "  vm-name                               Name for the instance. If it is"
  echo "                                        'primary' (the configured primary"
  echo "                                        instance name), the user's home"
  echo "                                        directory is mounted inside the newly"
  echo "                                        launced instance, in 'Home'."
  echo "                                        Default: primary"
}

#######################################
# EXECUTION
#######################################

#######################################
# Handling command line arguments
#######################################

if ! OPTS="$(getopt \
  --longoptions help,name:,email:,editor:,branch:,cpus:,disk:,\
memory:,ip:,mount: \
  --options hn:a:e:b:c:d:m:i: \
  --name "$(basename "$0")" \
  -- "$@"
)"; then
  usage
  exit 1
fi
eval set -- "$OPTS"
while true; do
  case "$1" in
    --help|-h) usage; exit ;;
    --name|-n) SETUP_ARGS+=( "--name=$2" ); shift 2 ;;
    --email|-a) SETUP_ARGS+=( "--email=$2" ); shift 2 ;;
    --editor|-e) SETUP_ARGS+=( "--editor=$2" ); shift 2 ;;
    --branch|-b) CHECKOUT_ARGS+=( "--branch=$2" ); shift 2 ;;
    --cpus|-c) CPUS="$2"; shift 2 ;;
    --disk|-d) DISK="$2"; shift 2 ;;
    --memory|-m) MEMORY="$2"; shift 2 ;;
    --ip|-i) IP="$2"; shift 2 ;;
    --mount) MOUNT="$2"; shift 2 ;;
    --) shift; break ;;
    *) echo "DEBUG: No implementation for the option $1" ; exit 1 ;;
  esac
done
ARGS=("$@")
ARGCOUNT=${#ARGS[@]}
if [ "$ARGCOUNT" -eq "1" ]; then
  VM_NAME="${ARGS[0]}"
elif [ "$ARGCOUNT" -gt "1" ]; then
  echo "Too many arguments supplied."
  usage
  exit 1
fi

#######################################
# Main Execution
#######################################

# Set VMU_HOME
if ! set_env; then echo "VMU Environment is not set."; exit 1; fi

# Install multipass if not installed
# and wait that multipassd is running.
setup-multipass

echo
echo "Creating and launching the $VM_NAME instance.."
LAUNCH=( "mp-launch -k -n $VM_NAME -c $CPUS -m $MEMORY -d $DISK" )
if [ $IP ]; then
  LAUNCH+=( "-i $IP" )
fi
if [ $MOUNT ];then
  LAUNCH+=( "--mount $MOUNT" )
fi
${LAUNCH[@]}

echo
echo "Setting up the VM:$VM_NAME for vm-utility development.."

echo
echo "Cloning vm-utility to the workspace from GitHub.."
cat $VMU_HOME/git/git-calls $VMU_HOME/development/dev-checkout | \
sed '/. git-calls/d' | \
multipass exec $VM_NAME -- bash -s -- "${CHECKOUT_ARGS[@]}"

echo
echo "Installing vm-utility.."
multipass exec $VM_NAME -- sudo $VMU_DIR/setup
multipass exec $VM_NAME -- vmu-config

cat $VMU_HOME/vmu-calls $VMU_HOME/git/git-calls \
$VMU_HOME/development/dev-vmu | \
sed '/. git-calls/d' | sed '/. vmu-calls/d' | \
multipass exec $VM_NAME -- bash -s -- "${SETUP_ARGS[@]}"
