#!/usr/bin/env bash
#
# Deletes and purges Multipass instance.
# Removes any known host keys with IP addresses of deleted instances.
# Removes any systemd services providing routes to the VMs from the host

set -e

. mp-calls

usage() {
  echo "Usage: $0 <name> [<name> ...]"
  echo
  echo "Deletes and purges Multipass instances."
  echo
  echo "Removes also any services, configurations and known host keys"
  echo "of the instances created by the VM-utility tool from the host."
  echo
  echo "Arguments:"
  echo "  name          Names of instances to delete"
}

if ! OPTS="$(getopt \
  --longoptions help \
  --options h \
  --name "$(basename "$0")" \
  -- "$@"
)"; then
  usage
  exit 1
fi
eval set -- "$OPTS"
while true; do
  case "$1" in
    --help|-h) usage; exit ;;
    --) shift; break ;;
    *) echo "DEBUG: No implementation for the option $1" ; exit 1 ;;
  esac
done
ARGS=("$@")
ARGCOUNT=${#ARGS[@]}
if [ "$ARGCOUNT" -eq "0" ]; then
  usage
  exit 1
fi

# delete and purge instances
if ! mp-delete -qp ${ARGS[@]}; then
  usage
  exit
fi
multipass list
