#!/usr/bin/env bash
set -e

# vm-utility installation
#
# Check usage below.

#######################################
# DEFAULT VALUES
#######################################

INTERACTIVE=
UTILITY_DIR="$(dirname -- "${BASH_SOURCE[0]}")"
DESTINATION="/usr/local/bin"

#######################################
# FUNCTIONS
#######################################

usage() {
  echo "Usage: $0 [options] [directory]"
  echo
  echo "Copies vm-utility tools to a single destination directory."
  echo "If no arguments are given the tools are made available for all"
  echo "users by copying them to /usr/local/bin."
  echo
  echo "Options:"
  echo "  -h, --help            Displays help on commandline options."
  echo "  -i, --interactive     Prompts before overwriting files"
  echo "                        in destination directory."
  echo "Arguments:"
  echo "  directory             Destination directory"
  echo "                        New directories are created as needed."
  echo "                        Default: /usr/local/bin"
}

#######################################
# EXECUTION
#######################################

#######################################
# Handling command line arguments
#######################################
if ! OPTS="$(getopt \
  --longoptions help,interactive \
  --options hi \
  --name "$(basename "$0")" \
  -- "$@"
)"; then
  usage
  exit 1
fi
eval set -- "$OPTS"
while true; do
  case "$1" in
    --help|-h)
      usage;
      exit
      ;;
    --interactive|-i)
      INTERACTIVE="-i"
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "DEBUG: No implementation for the option $1"
      exit 1
      ;;
  esac
done
ARGS=("$@")
ARGCOUNT=${#ARGS[@]}
if [ "$ARGCOUNT" -eq "1" ]; then
  DESTINATION="${ARGS[0]}"
elif [ "$ARGCOUNT" -gt "1" ]; then
  echo "Too many arguments supplied."
  usage
  exit 1
fi

#######################################
# Main Execution
#######################################

mkdir -p $DESTINATION
cp -v $INTERACTIVE \
  $UTILITY_DIR/multipass/mp-calls \
  $UTILITY_DIR/multipass/mp-ssh \
  $UTILITY_DIR/multipass/mp-launch \
  $UTILITY_DIR/multipass/mp-launch-usage \
  $UTILITY_DIR/jenkins/vm-agent/launch-vm-agent \
  $UTILITY_DIR/ssh/make-ssh-tunnel \
  $UTILITY_DIR/ssh/rm-ssh-tunnel \
  $UTILITY_DIR/ssh/ssh-tunnel-persistent.service \
  $UTILITY_DIR/installers/multipass/setup-multipass \
  $UTILITY_DIR/installers/docker/setup-docker \
  $UTILITY_DIR/installers/docker/docker-daemon.json \
  $UTILITY_DIR/installers/jenkins/dind/run_dind \
  $UTILITY_DIR/installers/jenkins/dind/jenkins.docker \
  $UTILITY_DIR/installers/jenkins/dind/run_jenkins \
  $UTILITY_DIR/development/config-nano \
  $UTILITY_DIR/development/config-git \
  $UTILITY_DIR/development/dev-vm \
  $UTILITY_DIR/development/purge-vm \
  $DESTINATION/.
echo "vm-utility installed."
